// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaDeGestaoEscolar.Data.Mapping;

namespace SistemaDeGestaoEscolar.Data.Mapping.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SistemaDeGestaoEscolar.Data.Domain.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Contacto")
                        .HasMaxLength(100)
                        .HasColumnType("int")
                        .HasColumnName("contacto");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Data_Nascimento")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<int>("Id_Disciplina")
                        .HasColumnType("int")
                        .HasColumnName("id_disciplina");

                    b.Property<int>("Idade")
                        .HasMaxLength(100)
                        .HasColumnType("int")
                        .HasColumnName("idade");

                    b.Property<string>("Morada")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("morada");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.Property<int>("Numero")
                        .HasMaxLength(100)
                        .HasColumnType("int")
                        .HasColumnName("numero");

                    b.HasKey("Id")
                        .HasName("pk_aluno");

                    b.HasIndex("Id_Disciplina")
                        .HasDatabaseName("idx_aluno_id_disciplina");

                    b.ToTable("aluno");
                });

            modelBuilder.Entity("SistemaDeGestaoEscolar.Data.Domain.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Carga_Horaria")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2")
                        .HasColumnName("carga_horaria");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Requisito")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("requisito");

                    b.HasKey("Id")
                        .HasName("pk_curso");

                    b.ToTable("curso");
                });

            modelBuilder.Entity("SistemaDeGestaoEscolar.Data.Domain.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Area")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("area");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Programa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("programa");

                    b.HasKey("Id")
                        .HasName("pk_disciplina");

                    b.ToTable("disciplina");
                });

            modelBuilder.Entity("SistemaDeGestaoEscolar.Data.Domain.Matricula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Data_Matricula")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2")
                        .HasColumnName("data_matricula");

                    b.Property<int>("IdAluno")
                        .HasColumnType("int")
                        .HasColumnName("id_aluno");

                    b.Property<int>("IdTurma")
                        .HasColumnType("int")
                        .HasColumnName("id_turma");

                    b.HasKey("Id")
                        .HasName("pk_matricula");

                    b.HasIndex("IdAluno")
                        .HasDatabaseName("idx_matricula_id_aluno");

                    b.HasIndex("IdTurma")
                        .HasDatabaseName("idx_matricula_id_turma");

                    b.ToTable("matricula");
                });

            modelBuilder.Entity("SistemaDeGestaoEscolar.Data.Domain.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Data_Nascimento")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<DateTime>("Hora")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2")
                        .HasColumnName("hora");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_professor");

                    b.ToTable("professor");
                });

            modelBuilder.Entity("SistemaDeGestaoEscolar.Data.Domain.Turma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Carga_Horaria")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2")
                        .HasColumnName("carga_horaria");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Data_Inicio")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2")
                        .HasColumnName("data_inicio");

                    b.Property<DateTime>("Data_final")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2")
                        .HasColumnName("data_final");

                    b.Property<int>("IdAluno")
                        .HasColumnType("int")
                        .HasColumnName("id_aluno");

                    b.Property<int>("IdProfessor")
                        .HasColumnType("int")
                        .HasColumnName("id_professor");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.Property<DateTime>("Periodo")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2")
                        .HasColumnName("periodo");

                    b.Property<int>("idCurso")
                        .HasColumnType("int")
                        .HasColumnName("id_curso");

                    b.HasKey("Id")
                        .HasName("pk_turma");

                    b.HasIndex("IdAluno")
                        .HasDatabaseName("idx_turma_id_aluno");

                    b.HasIndex("IdProfessor")
                        .HasDatabaseName("idx_turma_id_professor");

                    b.HasIndex("idCurso")
                        .HasDatabaseName("idx_turma_id_curso");

                    b.ToTable("turma");
                });

            modelBuilder.Entity("SistemaDeGestaoEscolar.Data.Domain.Aluno", b =>
                {
                    b.HasOne("SistemaDeGestaoEscolar.Data.Domain.Disciplina", "disciplina")
                        .WithMany()
                        .HasForeignKey("Id_Disciplina")
                        .HasConstraintName("fk_aluno_id_disciplina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("disciplina");
                });

            modelBuilder.Entity("SistemaDeGestaoEscolar.Data.Domain.Matricula", b =>
                {
                    b.HasOne("SistemaDeGestaoEscolar.Data.Domain.Aluno", "aluno")
                        .WithMany()
                        .HasForeignKey("IdAluno")
                        .HasConstraintName("fk_matricula_id_aluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaDeGestaoEscolar.Data.Domain.Turma", "turma")
                        .WithMany()
                        .HasForeignKey("IdTurma")
                        .HasConstraintName("fk_matricula_id_turma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("aluno");

                    b.Navigation("turma");
                });

            modelBuilder.Entity("SistemaDeGestaoEscolar.Data.Domain.Turma", b =>
                {
                    b.HasOne("SistemaDeGestaoEscolar.Data.Domain.Aluno", "aluno")
                        .WithMany()
                        .HasForeignKey("IdAluno")
                        .HasConstraintName("fk_turma_id_aluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaDeGestaoEscolar.Data.Domain.Professor", "professor")
                        .WithMany()
                        .HasForeignKey("IdProfessor")
                        .HasConstraintName("fk_turma_id_professor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaDeGestaoEscolar.Data.Domain.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("idCurso")
                        .HasConstraintName("fk_turma_id_curso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("aluno");

                    b.Navigation("Curso");

                    b.Navigation("professor");
                });
#pragma warning restore 612, 618
        }
    }
}
